import { Montserrat } from "next/font/google";

import Header from "./components/Header";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="container mx-auto m-2 font-display text-white w-1/11 lg:w-3/4">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
